In [538]:
import pandas as pd
import numpy as np

## Our Data

In [539]:
founders = pd.read_csv("data/Week 3/founders.csv")
op_founders = pd.read_csv("data/Week 3/onepager_founders.csv")
traction_perf = pd.read_csv("data/Week 3/onepager_traction_and_performance.csv")
traction_perf_1 = pd.read_csv("data/Week 1/onepager_traction_and_performance.csv")

## Feature Evaluation 

1. Complete profile 
2. Metric card 
3. Most recent update/creation
4. Time from signup to last update

### 1. Complete Profile

In [540]:
founders.head()

,uuid,image_key,name,title,links,bio,created_at,updated_at
0,0011279a-0c95-4f3d-8ae0-a0916fe54afd,8ea8552e-0588-4c8c-b2ff-30ba76349136,Will Valori,Founder,"{""linkedin"": ""https://www.linkedin.com/in/will...","Strategy at BCG, early childhood education at ...",2020-08-17 19:29:54,2020-10-27 15:51:19
1,0014bb20-d843-42f5-8af4-d30de649e1f9,186f81e4-762b-4e6a-b0a5-5bb454e74410,Saad Usmani,Founder & CEO,"{""linkedin"": ""https://www.linkedin.com/in/saad...","Currently, 23, I've founded AirwaysX with an a...",2020-09-17 16:04:17,2020-10-21 15:11:40
2,004a3eee-e647-4495-bc42-a7e588acb32d,a39ea233-6d97-4d79-b044-86e5e009d453,Mat Sherman,Founder,"{""twitter"": ""http://twitter.com/mat_Sherman/""}","Mat is the founder of FWD. Before FWD, Mat ran...",2020-12-23 17:33:15,2020-12-23 23:08:13
3,004d7015-53dd-4f0d-81f6-a33e53ee537c,6a35784c-565d-466b-b46a-8d8fbd231e7f,Laura Robbins,COO & Co-Founder,"{""linkedin"": ""https://www.linkedin.com/in/laur...",Ms. Robbins is the COO of Advocatia. Ms. Robbi...,2020-12-17 20:45:24,2021-01-10 00:15:43
4,00551a38-1494-464d-9e2e-9592ac704a1a,NaN,Mike Gillan,CTO & Co-Founder,"{""linkedin"": ""https://www.linkedin.com/in/mike...","Mike is a security architect, leader, entrepre...",2020-09-28 11:36:27,2020-09-28 11:36:27

In [541]:
op_founders.head()

,onepager_uuid,founder_uuid,created_at,updated_at
0,9f452da8-2745-45d2-85ec-2d5a48aed684,0014bb20-d843-42f5-8af4-d30de649e1f9,2020-09-17 16:04:17,2020-09-17 16:04:17
1,29d43a79-4d5f-4fa6-a07d-b60225839117,004a3eee-e647-4495-bc42-a7e588acb32d,2020-12-23 17:33:15,2020-12-23 17:33:15
2,137b5e24-9202-4fba-aff7-de9284dad021,00551a38-1494-464d-9e2e-9592ac704a1a,2020-09-28 11:36:27,2020-09-28 11:36:27
3,9112231a-0d88-45e4-9fba-13a82186bfb9,006253fb-1b35-4153-8acd-c3bd9f583c73,2020-10-21 18:11:35,2020-10-21 18:11:35
4,d078a038-a893-4fb2-b780-0e35209ca549,00658ab5-262d-4f38-ad46-de219850d199,2021-02-23 03:07:42,2021-02-23 03:07:42

In [542]:
# left join founders and op_founders 
founder_onepager = pd.merge(founders, op_founders, how = "left", left_on = "uuid", right_on = "founder_uuid").drop(columns = {"founder_uuid","created_at_y", "updated_at_y"})

In [544]:
# added "has complete profile" and "has one pager" columns to founder_onepager

complete_profiles = founders.copy().dropna()["uuid"]
founder_onepager["has complete profile"] = founder_onepager["uuid"].isin(complete_profiles.tolist())
founder_onepager["has onepager"] = founder_onepager["onepager_uuid"].notna()
founder_onepager.head()

,uuid,image_key,name,title,links,bio,created_at_x,updated_at_x,onepager_uuid,has complete profile,has onepager
0,0011279a-0c95-4f3d-8ae0-a0916fe54afd,8ea8552e-0588-4c8c-b2ff-30ba76349136,Will Valori,Founder,"{""linkedin"": ""https://www.linkedin.com/in/will...","Strategy at BCG, early childhood education at ...",2020-08-17 19:29:54,2020-10-27 15:51:19,NaN,True,False
1,0014bb20-d843-42f5-8af4-d30de649e1f9,186f81e4-762b-4e6a-b0a5-5bb454e74410,Saad Usmani,Founder & CEO,"{""linkedin"": ""https://www.linkedin.com/in/saad...","Currently, 23, I've founded AirwaysX with an a...",2020-09-17 16:04:17,2020-10-21 15:11:40,9f452da8-2745-45d2-85ec-2d5a48aed684,True,True
2,004a3eee-e647-4495-bc42-a7e588acb32d,a39ea233-6d97-4d79-b044-86e5e009d453,Mat Sherman,Founder,"{""twitter"": ""http://twitter.com/mat_Sherman/""}","Mat is the founder of FWD. Before FWD, Mat ran...",2020-12-23 17:33:15,2020-12-23 23:08:13,29d43a79-4d5f-4fa6-a07d-b60225839117,True,True
3,004d7015-53dd-4f0d-81f6-a33e53ee537c,6a35784c-565d-466b-b46a-8d8fbd231e7f,Laura Robbins,COO & Co-Founder,"{""linkedin"": ""https://www.linkedin.com/in/laur...",Ms. Robbins is the COO of Advocatia. Ms. Robbi...,2020-12-17 20:45:24,2021-01-10 00:15:43,NaN,True,False
4,00551a38-1494-464d-9e2e-9592ac704a1a,NaN,Mike Gillan,CTO & Co-Founder,"{""linkedin"": ""https://www.linkedin.com/in/mike...","Mike is a security architect, leader, entrepre...",2020-09-28 11:36:27,2020-09-28 11:36:27,137b5e24-9202-4fba-aff7-de9284dad021,False,True

### 2. Metric Card

In [545]:
traction_perf.head()

,uuid,onepager_uuid,acronym,parent_metric,sub_metric,time_period,metric_value,prefix,suffix,order,created_at,updated_at
0,01dc18cc-fc13-47c4-a4ab-0acb49bab331,2141b6b9-d0b0-4c0f-b8db-50dbe5c5069d,RTN,Revenue and Sales,Total Addressable Market,NaN,1.400000e+13,$,NaN,1,2021-02-27 03:53:57,2021-02-27 03:53:57
1,02940790-1992-4fcc-800d-fdbde2a06a7f,94f69d52-b733-40d5-932d-a91d7ecc382d,URM,Users,User Retention,per month,7.000000e+01,NaN,%,5,2021-02-21 21:17:24,2021-03-03 15:01:24
2,02b0505e-cc3b-4a23-9812-c59425013638,22f04020-b76b-45e0-a197-94c6aba7a71b,CNLM,Customer Value,Net Promoter Score,last month,9.800000e+00,NaN,NaN,1,2021-01-29 21:19:44,2021-01-29 21:20:59
3,038ef131-4b3d-434d-a4e6-04ffdb6f8635,d880543d-7055-4169-8c21-a5afea2fd6be,CCAT,Customer Value,Customer Acquisition Cost,all time,0.000000e+00,$,NaN,3,2021-02-19 02:01:57,2021-03-02 21:54:44
4,03c5f718-a4e6-40e5-9d79-23f47ab21db0,5c6f9f14-9028-4d62-b8a8-6b16dee3f5e1,RRM,Revenue and Sales,Recurring Revenue,per month,4.200000e+03,$,NaN,1,2021-02-23 11:56:57,2021-03-02 15:01:13

In [546]:
# minimal data but better than last week with only 39 
print("number of metric card users:", traction_perf.shape[0])

number of metric card users: 215

In [534]:
# after 2/17 w/ introduction of metrics card 
traction_perf["created_at"] = traction_perf["created_at"].str.extract(r'(\d{4}-0(2|3)-\d{2})')
traction_perf = traction_perf.sort_values("created_at", ascending = True)

after_mcard = traction_perf.dropna(subset = ["created_at"])
founders_w_mcard = after_mcard["onepager_uuid"]

In [549]:
# added "has metric card" column to founder_onepager
founder_onepager["has metric card"] = founder_onepager["onepager_uuid"].isin(founders_w_mcard.tolist())
founder_onepager.head()

,uuid,image_key,name,title,links,bio,created_at_x,updated_at_x,onepager_uuid,has complete profile,has onepager,has metric card,updated within 30 days
0,0011279a-0c95-4f3d-8ae0-a0916fe54afd,8ea8552e-0588-4c8c-b2ff-30ba76349136,Will Valori,Founder,"{""linkedin"": ""https://www.linkedin.com/in/will...","Strategy at BCG, early childhood education at ...",2020-08-17 19:29:54,2020-10-27 15:51:19,NaN,True,False,False,False
1,0014bb20-d843-42f5-8af4-d30de649e1f9,186f81e4-762b-4e6a-b0a5-5bb454e74410,Saad Usmani,Founder & CEO,"{""linkedin"": ""https://www.linkedin.com/in/saad...","Currently, 23, I've founded AirwaysX with an a...",2020-09-17 16:04:17,2020-10-21 15:11:40,9f452da8-2745-45d2-85ec-2d5a48aed684,True,True,False,False
2,004a3eee-e647-4495-bc42-a7e588acb32d,a39ea233-6d97-4d79-b044-86e5e009d453,Mat Sherman,Founder,"{""twitter"": ""http://twitter.com/mat_Sherman/""}","Mat is the founder of FWD. Before FWD, Mat ran...",2020-12-23 17:33:15,2020-12-23 23:08:13,29d43a79-4d5f-4fa6-a07d-b60225839117,True,True,False,False
3,004d7015-53dd-4f0d-81f6-a33e53ee537c,6a35784c-565d-466b-b46a-8d8fbd231e7f,Laura Robbins,COO & Co-Founder,"{""linkedin"": ""https://www.linkedin.com/in/laur...",Ms. Robbins is the COO of Advocatia. Ms. Robbi...,2020-12-17 20:45:24,2021-01-10 00:15:43,NaN,True,False,False,False
4,00551a38-1494-464d-9e2e-9592ac704a1a,NaN,Mike Gillan,CTO & Co-Founder,"{""linkedin"": ""https://www.linkedin.com/in/mike...","Mike is a security architect, leader, entrepre...",2020-09-28 11:36:27,2020-09-28 11:36:27,137b5e24-9202-4fba-aff7-de9284dad021,False,True,False,False

#### Question: 

1. What column "created_at" or "updated_at" do I use to determine whether or not they used metric card (after 2/17)?  Or do I assume that all the entries in this dataset are those who filled out metrics card?

### Onepager updated within 30 days 

Assume latest data is 3/5, so look at companies' whose last update is around 2/1: 
1. new users 
2. old users who have been updating their onepager **

In [550]:
# a lil bit of data cleaning first! keeping only data past 2/5
founder_onepager = founder_onepager.rename(columns = {"created_at_x": "created_at", "updated_at_x": "updated_at"})
founder_onepager["created_at"] = founder_onepager["created_at"].str.extract(r'(\d{4}-\d{2}-\d{2})')
founder_onepager["updated_at"] = founder_onepager["updated_at"].str.extract(r'(\d{4}-\d{2}-\d{2})')

recent_update = founder_onepager.copy() 
recent_update["updated_at"] = recent_update["updated_at"].str.extract(r'(\d{4}-0(2|3)-\d{2})')
recent_update = recent_update.sort_values("updated_at", ascending = False)
recent_update = recent_update.dropna(subset = ["updated_at"])
print("number of new users/recent updates:", recent_update.shape[0])
#recent_update.head()

number of new users/recent updates: 1146

In [551]:
# filter out new users (defined to be those who created onepager on 3/5)
#new_user_index = sum([date == '2021-03-05' for date in recent_update["created_at"].tolist()])
#recent_update = recent_update.iloc[new_user_index:]
print("number of users who's creation and update are different:", sum(recent_update["created_at"] != recent_update["updated_at"]))
print("number of users who's creation and update are the same:", sum(recent_update["created_at"] == recent_update["updated_at"]))
recent_update.head()

number of users who's creation and update are different: 708
number of users who's creation and update are the same: 438

,uuid,image_key,name,title,links,bio,created_at,updated_at,onepager_uuid,has complete profile,has onepager,has metric card,updated within 30 days
2076,c9ac17bc-95f6-41f6-957d-2cdd4e7fa733,129abcca-262b-4f66-9563-4ca41ab15780,Dr. Alexandria Reyes,CEO-Founder,"{""twitter"": ""https://twitter.com/relyonhardwor...","Educator, Entrepreneur, Advocate for Change i...",2021-02-26,2021-03-05,7d13b2c1-fee0-49eb-906f-5c9fe50c7f29,True,True,True,True
1348,80c0d067-0b4e-40ce-b47a-c6c933c5a593,NaN,Jennifer Huang,Founder & CEO,{},"A passionate, resilient entrepreneur with stro...",2021-03-04,2021-03-05,6d7b1ab6-467b-4b87-a7a9-978a5b37b2af,False,True,False,True
577,38d2a897-8824-42e3-ba29-8d7c57d1de19,6fff515b-e026-455e-8334-e291b61a74e5,DeAnna Tipton,Co-Founder,"{""twitter"": """", ""website"": """", ""facebook"": """",...",During the day DeAnna is a senior data scienti...,2021-03-03,2021-03-05,197a5c35-fcab-448d-a0bc-cb8e89f207fd,True,True,False,True
1974,c0338e6c-85d8-416a-832d-83716a01dc95,a765634a-5f16-43a2-88be-57f6a7573be3,Alizeh Kahlifa,Marketing,"{""twitter"": """", ""website"": """", ""facebook"": """",...",An organized and creative professional with ex...,2021-03-05,2021-03-05,b06aeea5-ffe6-4d84-ba83-b5c22568b8c8,True,True,False,True
713,44f3d86e-eb85-4e73-b417-df9a10238e56,NaN,Yiming Dong,Co-Founder & COO,{},Ph.D. Synthetic Biology @ Peking University,2021-03-05,2021-03-05,bce2380d-a26e-4fc8-9801-125aabd17bde,False,True,False,True

In [552]:
founder_onepager["updated within 30 days"] = founder_onepager['uuid'].isin(recent_update["uuid"])
founder_onepager = founder_onepager.sort_values("updated_at", ascending = False)
founder_onepager.head()

,uuid,image_key,name,title,links,bio,created_at,updated_at,onepager_uuid,has complete profile,has onepager,has metric card,updated within 30 days
410,29871719-cdb9-4707-92d3-00b9867c59db,eefbe5cd-0301-4c9a-bb5c-15f925766974,Jason Woodman,"Principal Architect, Kubernetes Certified Arch...","{""twitter"": """", ""website"": """", ""facebook"": """",...",After getting his start in the industry as a s...,2021-03-05,2021-03-05,945b8fa0-8361-4f0e-9289-67cc85c0f97c,True,True,False,True
2076,c9ac17bc-95f6-41f6-957d-2cdd4e7fa733,129abcca-262b-4f66-9563-4ca41ab15780,Dr. Alexandria Reyes,CEO-Founder,"{""twitter"": ""https://twitter.com/relyonhardwor...","Educator, Entrepreneur, Advocate for Change i...",2021-02-26,2021-03-05,7d13b2c1-fee0-49eb-906f-5c9fe50c7f29,True,True,True,True
168,1204c18e-8a0f-4432-ba74-04c045acbf99,e83d13d5-1487-486f-bb19-84e2b720f82b,Bill Myers,CTO,{},I started my career with Apple as a Business S...,2021-03-01,2021-03-05,b06aeea5-ffe6-4d84-ba83-b5c22568b8c8,True,True,False,True
749,48458d36-c3af-49a0-9e64-b9362bb42054,NaN,Jane Doe,Adviser,{},Accomplished architect for 15 years. AIA LEED ...,2021-03-01,2021-03-05,1a7eabf9-4dc5-4754-8602-582e03c6a790,False,True,True,True
1899,b7b3b5c1-9aa9-43a8-9842-1b9767978eae,fe53f6f6-d8c0-4cf8-96a4-99e5ebb12a8a,Rosalind Marinou,Founder / CEO,"{""twitter"": """", ""website"": """", ""facebook"": """",...",From a culturally enriched childhood in Los An...,2021-03-01,2021-03-05,4d1813b0-8460-4782-8dcc-02556d809d79,True,True,False,True

#### Question: 
1. When in March was week 3 data acquired? 3/5? 
2. How are we defining "recent"? 
3. How to separate new user from older user? Past x amount of days they are no longer considered new user and we can start looking at their "update" data?

### Time from signup to last update

In [520]:
update_time = founder_onepager.copy()
update_time = update_time.dropna(subset = ["onepager_uuid"])
update_time["created_at"] = update_time["created_at"].str.extract(r'(\d{4}-\d{2}-\d{2})')
update_time["updated_at"] = update_time["updated_at"].str.extract(r'(\d{4}-\d{2}-\d{2})')

update_time['created_at'] = pd.to_datetime(update_time['created_at'])
update_time['updated_at'] = pd.to_datetime(update_time["updated_at"])

founder_onepager["signup to update time (days)"] = (update_time["updated_at"] - update_time["created_at"]) / np.timedelta64(1, 'D')
#founder_onepager.head()

### Aggregated Dataset

In [521]:
features = founder_onepager.copy()
features = features.drop(columns = {"image_key", "title", "links", "bio", "onepager_uuid", "name", "created_at", "updated_at"}).set_index("uuid")
features

,has complete profile,has onepager,has metric card,updated within 30 days,signup to update time (days)
uuid,,,,,
29871719-cdb9-4707-92d3-00b9867c59db,True,True,False,True,0.0
c9ac17bc-95f6-41f6-957d-2cdd4e7fa733,True,True,True,True,7.0
1204c18e-8a0f-4432-ba74-04c045acbf99,True,True,False,True,4.0
48458d36-c3af-49a0-9e64-b9362bb42054,False,True,True,True,4.0
b7b3b5c1-9aa9-43a8-9842-1b9767978eae,True,True,False,True,4.0
...,...,...,...,...,...
d6c1ae5d-c04d-41c0-9c63-244db8d23e10,True,True,False,False,1.0
306dae1d-7a78-477f-8395-6eac76136d1f,False,False,False,False,NaN
c95edec3-e87d-4d99-b532-72066f5da42e,False,True,False,False,0.0
eb899a85-4503-4a3a-991e-4422bbe85052,False,True,False,False,0.0
79f458e5-d8a3-4804-98b8-56d74fcb8fe9,False,True,False,False,0.0

### Correlation Matrix

In [522]:
features.corr()

,has complete profile,has onepager,has metric card,updated within 30 days,signup to update time (days)
has complete profile,1.000000,0.022578,0.128960,0.057960,0.270512
has onepager,0.022578,1.000000,0.156311,0.237052,NaN
has metric card,0.128960,0.156311,1.000000,0.339112,0.065313
updated within 30 days,0.057960,0.237052,0.339112,1.000000,0.160657
signup to update time (days),0.270512,NaN,0.065313,0.160657,1.000000